# Generated by Django 3.1.13 on 2021-12-23 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_enabled', models.BooleanField(default=True, help_text='Is enabled', verbose_name='is enabled')),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ad_url', models.CharField(max_length=1000)),
                ('monthly_budget', models.IntegerField()),
                ('stripe_id', models.CharField(blank=True, max_length=75, null=True)),
                ('is_valid_payment', models.BooleanField(default=False, help_text='Is valid payment', verbose_name='is valid payment')),
                ('approved', models.BooleanField(default=False, help_text='Is approved', verbose_name='approved')),
                ('ad_sizes', models.ManyToManyField(to='advertisers.AdSize')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertiser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
