# Generated by Django 3.1.13 on 2022-01-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_ad_adbrand'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adsize',
            constraint=models.UniqueConstraint(fields=('width', 'height'), name='unique size'),
        ),
    ]
