# Generated by Django 3.1.14 on 2022-03-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_auto_20220119_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Set null for popup ads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='advertisers.adsize'),
        ),
    ]
