# Generated by Django 3.1.14 on 2022-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_auto_20220307_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbrand',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Designates whether this brand is enabled.', verbose_name='is enabled'),
        ),
    ]
