# Generated by Django 3.1.13 on 2021-10-27 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_reflinks', '0002_referralhit_http_referer'),
        ('accounts', '0003_payoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileReferralHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_hit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_reflinks.referralhit')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
