# Generated by Django 3.1.13 on 2021-11-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofilereferralhit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='user_profile_referral_hit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='accounts.userprofilereferralhit'),
        ),
    ]
