# Generated by Django 3.1.13 on 2021-11-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payout_user_profile_referral_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilereferralhit',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_referral_hits', to=settings.AUTH_USER_MODEL),
        ),
    ]
