# Generated by Django 3.0.14 on 2021-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('number_of_click', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.IntegerField(choices=[(0, 'Google'), (1, 'Guppy')], default=0)),
                ('search_terms', models.TextField(blank=True)),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('search_results', models.ManyToManyField(related_name='search', to='search.Result')),
            ],
        ),
    ]
