# Generated by Django 3.1.9 on 2021-06-08 07:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('last_origin', models.URLField(blank=True, max_length=2048)),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
