# Generated by Django 3.1.9 on 2021-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210702_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
