# Generated by Django 3.1.9 on 2021-08-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210702_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['pk']},
        ),
    ]
