# Generated by Django 3.1.9 on 2021-08-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210823_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['pk']},
        ),
    ]
