---
name: Run black
on:
  - push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: install black
        run: pip install black==20.8b1
      - name: Black
        run: black . --check
