---
name: Run isort
on:
  - push

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - uses: isort/isort-action@master
