---
name: Run mypy
on:
  - push

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: apt update
        run: sudo apt update
      - uses: niden/actions-memcached@v7
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: memcached dependencies
        run: sudo apt install libmemcached-dev
      - name: Cache Python environment
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: |
            ${{ env.pythonLocation }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ env.pythonLocation }}-pip-
            ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
      - name: MyPy
        run: mypy .
