---
name: Run pylint
on:
  - push

jobs:
  lint:
    env:
      DJANGO_SETTINGS_MODULE: settings.local
    runs-on: ubuntu-latest
    steps:
      - name: apt update
        run: sudo apt update
      - uses: niden/actions-memcached@v7
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: memcached dependencies
        run: sudo apt-get install libmemcached-dev
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
      - name: Pylint
        run: pylint accounts guppy search
