---
name: Run shellcheck
on:
  - push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        run: shellcheck bin/*.sh bin/*/*.sh
